config/routes.rb
Rails.application.routes.draw do

resources :messages do
  member do
    put :archive
  end
  collection do
    put :archive_all
  end
end

devise_for :users

devise_scope :user do
  authenticated :user do
    root 'messages#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
 scope :by_user_received, -> (user_received_id) { where(user_received_id: user_received_id) }
 scope :not_archive, -> { where(:archive => false) }

 def self.create_message(message_params,user)
   user_received = User.where(email: message_params[:user_received_id]).first
   if !user_received.blank?
     message = Message.new(message_params)
     message.user_send_id = user.id
     message.user_received_id = user_received.id
     self.generate_date_send(message)
     message.read = false
     message.save
   end
 end

 def self.archive(message_id)
   message = Message.find(message_id)
   message.update(archive: true)
 end

 def self.generate_date_send(message)
   date = Time.zone.now - 3.hours 
   message.update(date_send: date)
 end

def self.archive_all(messages)
  messages.each do |message|
    message.update(archive: true)
  end
end

def self.set_read(params)
  date = Time.zone.now - 3.hours
  message = Message.find(params[:id])
  message.update(date_read: date)
  message.update(read: true)
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.by_user_received(current_user.id).not_archive.order(date_send: :DESC)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @messages = Message.set_read(params)
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  def archive
    message_id = params[:id]
    @message = Message.archive(message_id)

    respond_to do |format|
      if !@message.nil?
        format.html { redirect_to messages_url notice: 'Mensagens arquivadas com sucesso' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def archive_all
    @messages = Message.by_user_received(current_user.id).not_archive
    Message.archive_all(@messages)

    respond_to do |format|
      if !@messages.nil?
        format.html { redirect_to messages_url notice: 'Mensagem arquivadas com sucesso' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.create_message(message_params,current_user)

    respond_to do |format|
      if !@message.nil?
        format.html { redirect_to messages_url notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:send, :read, :date_send, :date_read, :text, :user_id, :user_send_id, :user_received_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.erb
<h1> tá logado manooo </h1>
<li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Email</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :email_para_envio %>
    <%= f.email_field :user_received_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Mensagens</h1>
<button ><%= link_to 'Arquivar todas', archive_all_messages_path , method: :put%> </button>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Mensagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <!-- <td id="message"><%= link_to message.text, message_path(message) %> </td>-->
        <% if message.read ==  false %>
          <td><b><%= link_to message.text, message_path(message) %></b></td>
        <% else %>
          <td><%= link_to message.text, message_path(message) %> </td>
      <% end %>
        <td><button><%= link_to 'Arquivar', archive_message_path(message),method: :put %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-default btn-sm glyphicon glyphicon-envelope"><%= link_to 'Escreva uma nova mensagem', new_message_path %> <br></button> <br>

<%= link_to('Logout', destroy_user_session_path, method: :delete) %> 

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Send:</strong>
  <%= @message.send %>
</p>

<p>
  <strong>Read:</strong>
  <%= @message.read %>
</p>

<p>
  <strong>Date send:</strong>
  <%= @message.date_send %>
</p>

<p>
  <strong>Date read:</strong>
  <%= @message.date_read %>
</p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>